version: '3'
services:
  mongdb:
    image: mongo
    networks:
      - mrr
    ports:
      - 27017:27017
  server:
    image: mrr-golang
    networks:
      - mrr
    environment:
      - MONGO_HOSTNAME=mongdb
      - MONGO_DB=mrr
    ports:
      - 8080:8080
  html:
     image: mrr-html
     build: .
     networks:
       - mrr
     volumes:
       - ./nginx/:/etc/nginx/conf.d/
       - ./html/:/usr/share/nginx/html/
     ports:
       - 80:80
networks:
  mrr:
    driver: bridge